source 'https://cdn.cocoapods.org/'

platform :ios, '11.0'
use_frameworks!
inhibit_all_warnings!

target 'Boardy_Example' do
  pod 'Boardy', :path => '../'
  pod 'Boardy/ComponentKit', :path => '../'
  pod 'Boardy/DeepLink', :path => '../'
  pod 'Boardy/Composable', :path => '../'
  pod 'Boardy/RxStoreRef', :path => '../'
  pod 'UIComposable/DiffUI' #, :git => 'https://github.com/congncif/UIComposable.git', :branch => 'master'
  
#  pod 'ReferenceStoreManager', :git => 'https://github.com/congncif/RxReferenceStoreManager.git'
  
  pod 'RIBs' , :git => 'https://github.com/uber/RIBs.git', :branch => 'master'
  pod 'ViewStateCore'
  pod 'SiFUtilities'
  pod 'Resolver' , '~> 1.1'

  target 'Boardy_Tests' do
    inherit! :search_paths
  end
end
