//
//  ServiceMap.swift
//  Boardy
//
//  Created by NGUYEN CHI CONG on 27/02/2023.
//

import Foundation

/// The typed entry point a module exposes to the rest of the app.
///
/// A module publishes accessors on its service map instead of exporting board identifiers, so a
/// caller navigates to a feature without knowing how it is built. It also gives one place to see
/// every service the app has.
/// ```
/// // 1. Extend ServiceMap
/// public extension ServiceMap {
///     var transportation: TransportationServiceMap {
///         TransportationServiceMap(mainboard: mainboard)
///     }
/// }
///
///// 2. Define service map for a service
/// public struct TransportationServiceMap {
///     let mainboard: FlowMotherboard
///
///     public var status: TransportationStatusMainDestination {
///         mainboard.ioTransportationStatus()
///     }
/// }
/// ```
/// ```
/// // 3. Activate a service using ServiceMap
/// func checkTransportationStatus() {
///     motherboard.serviceMap.transportation.status.activate()
/// }
/// ```
///
/// Generated by the Xcode templates; see `docs/ServiceMap.md`.
open class ServiceMap {
    public let mainboard: FlowMotherboard

    public required init(mainboard: FlowMotherboard) {
        self.mainboard = mainboard
    }
}

public extension MotherboardType where Self: FlowManageable {
    var serviceMap: ServiceMap {
        ServiceMap(mainboard: self)
    }
}

public extension IdentifiableBoard {
    var serviceMap: ServiceMap {
        if let motherboard = delegate as? FlowMotherboard {
            return motherboard.serviceMap
        } else {
            preconditionFailure("❌ [Boardy] Cannot be found `serviceMap` due to the board \(identifier) was not installed into any motherboard!")
        }
    }
}

public extension ServiceMap {
    func link<MapType: ServiceMap>(_: MapType.Type = MapType.self) -> MapType {
        MapType(mainboard: mainboard)
    }
}
